import type { Question } from '@/types/survey'

export const questions: Question[] = [
  // ===== BLOCK A — Demographics =====
  {
    id: 'A1',
    block: 'A',
    zh: '您的年龄是？',
    ru: 'Ваш возраст?',
    type: 'single',
    fieldName: 'age',
    options: [
      { id: 'under18', zh: '18岁以下', ru: 'До 18 лет' },
      { id: '18-22', zh: '18–22岁', ru: '18–22 года' },
      { id: '23-27', zh: '23–27岁', ru: '23–27 лет' },
      { id: '28-35', zh: '28–35岁', ru: '28–35 лет' },
      { id: '36plus', zh: '36岁以上', ru: '36+ лет' },
    ],
  },
  {
    id: 'A2',
    block: 'A',
    zh: '您的性别是？',
    ru: 'Ваш пол?',
    type: 'single',
    fieldName: 'gender',
    options: [
      { id: 'male', zh: '男', ru: 'Мужской' },
      { id: 'female', zh: '女', ru: 'Женский' },
      { id: 'prefer_not', zh: '不便透露', ru: 'Предпочитаю не отвечать' },
    ],
  },
  {
    id: 'A3',
    block: 'A',
    zh: '您目前的主要身份是？',
    ru: 'Ваш основной род деятельности?',
    type: 'single',
    fieldName: 'occupation',
    options: [
      { id: 'bachelor', zh: '本科生', ru: 'Студент бакалавриата' },
      { id: 'master_phd', zh: '硕士/博士研究生', ru: 'Магистрант / аспирант' },
      { id: 'worker', zh: '上班族', ru: 'Работающий' },
      { id: 'freelancer', zh: '自由职业/创业者', ru: 'Фрилансер / предприниматель' },
      { id: 'other', zh: '其他', ru: 'Другое' },
    ],
  },

  // ===== BLOCK B — Content Consumption =====
  {
    id: 'B1',
    block: 'B',
    zh: '您会为哪些类型的内容付费？（可多选）',
    ru: 'За какой тип контента вы готовы платить?',
    type: 'multiple',
    fieldName: 'paidContentTypes',
    options: [
      { id: 'music', zh: '音乐/音频', ru: 'Музыка / аудио' },
      { id: 'short_video', zh: '短视频（如抖音、快手风格）', ru: 'Короткие видео' },
      { id: 'long_video', zh: '长视频/纪录片', ru: 'Длинные видео / документалки' },
      { id: 'photo', zh: '摄影作品/照片/壁纸', ru: 'Фото / принты / обои' },
      { id: 'design', zh: '设计素材（模板、字体、插画等）', ru: 'Дизайн-ресурсы' },
      { id: 'livestream', zh: '直播内容/打赏', ru: 'Лайв-стримы / донаты' },
      { id: 'never_pay', zh: '我从不为内容付费', ru: 'Никогда не плачу за контент' },
    ],
  },
  {
    id: 'B2',
    block: 'B',
    zh: '您每月在数字内容上大约花费多少？（音乐、视频、照片等）',
    ru: 'Сколько тратите в месяц на цифровой контент?',
    type: 'single',
    fieldName: 'monthlySpend',
    skipIf: { field: 'paidContentTypes', includes: 'never_pay' },
    options: [
      { id: '0', zh: '0元（不花钱）', ru: '0¥' },
      { id: '1-30', zh: '1–30元', ru: '1–30¥' },
      { id: '31-100', zh: '31–100元', ru: '31–100¥' },
      { id: '101-300', zh: '101–300元', ru: '101–300¥' },
      { id: '300plus', zh: '300元以上', ru: '300+¥' },
    ],
  },
  {
    id: 'B3',
    block: 'B',
    zh: '您最常使用哪些平台来观看或收听内容？（最多选5个）',
    ru: 'На каких платформах потребляете контент?',
    type: 'multiple',
    fieldName: 'platforms',
    maxChoices: 5,
    options: [
      { id: 'douyin', zh: '抖音', ru: 'Douyin (TikTok)' },
      { id: 'red', zh: '小红书', ru: 'Xiaohongshu (RED)' },
      { id: 'bilibili', zh: '哔哩哔哩 (B站)', ru: 'Bilibili' },
      { id: 'wechat_ch', zh: '微信视频号', ru: 'WeChat Channels' },
      { id: 'netease', zh: '网易云音乐', ru: 'NetEase Music' },
      { id: 'qq_music', zh: 'QQ音乐', ru: 'QQ Music' },
      { id: 'kuaishou', zh: '快手', ru: 'Kuaishou' },
      { id: 'taobao_live', zh: '淘宝直播', ru: 'Taobao Live' },
      { id: 'youtube_ig', zh: 'YouTube/Instagram（通过VPN）', ru: 'YouTube / Instagram' },
      { id: 'other', zh: '其他', ru: 'Другое' },
    ],
  },
  {
    id: 'B4',
    block: 'B',
    zh: '您对以下哪些内容主题最感兴趣？（最多选5个）',
    ru: 'Какие темы контента вам интересны?',
    type: 'multiple',
    fieldName: 'contentTopics',
    maxChoices: 5,
    options: [
      { id: 'exotic_culture', zh: '异国文化体验', ru: 'Экзотический культурный опыт' },
      { id: 'city_vlog', zh: '城市探索/旅行Vlog', ru: 'Городские прогулки / тревел' },
      { id: 'food', zh: '美食探店/烹饪', ru: 'Еда / рестораны / готовка' },
      { id: 'music_covers', zh: '原创音乐/翻唱', ru: 'Авторская музыка / каверы' },
      { id: 'photo_art', zh: '摄影教程/艺术创作', ru: 'Фото-уроки / арт' },
      { id: 'winter_sport', zh: '冬季运动/户外探险', ru: 'Зимний спорт / outdoor' },
      { id: 'fashion', zh: '时尚/生活方式', ru: 'Мода / лайфстайл' },
      { id: 'education', zh: '学习/教育类内容', ru: 'Обучение / образование' },
      { id: 'cn_ru_exchange', zh: '中俄文化交流', ru: 'Китайско-русский обмен' },
      { id: 'gaming_anime', zh: '游戏/动漫相关', ru: 'Игры / аниме' },
    ],
  },
  {
    id: 'B5',
    block: 'B',
    zh: '对您来说，外国创作者的内容最吸引您的是什么？（请排出前三名）',
    ru: 'Что делает зарубежный контент привлекательным? (ТОП-3)',
    type: 'ranking',
    fieldName: 'appealFactors',
    rankTop: 3,
    options: [
      { id: 'unique_angle', zh: '独特的视角和风格', ru: 'Уникальный ракурс / стиль' },
      { id: 'high_quality', zh: '高质量的制作水平', ru: 'Высокое качество продакшена' },
      { id: 'cultural_fresh', zh: '文化差异带来的新鲜感', ru: 'Свежесть от культурного различия' },
      { id: 'practical', zh: '实用价值（学到东西）', ru: 'Практическая ценность' },
      { id: 'emotional', zh: '情感共鸣', ru: 'Эмоциональный резонанс' },
      { id: 'fair_price', zh: '合理的价格', ru: 'Адекватная цена' },
    ],
  },

  // ===== BLOCK C — Russian Far East Creative Industries Attitude =====
  {
    id: 'C1',
    block: 'C',
    zh: '您是否接触过来自俄罗斯远东地区的创意内容？',
    ru: 'Знакомы ли вы с креативным контентом с Дальнего Востока России?',
    type: 'single',
    fieldName: 'vlkContentAware',
    options: [
      { id: 'often', zh: '是的，经常看到', ru: 'Да, регулярно' },
      { id: 'sometimes', zh: '偶尔看到过', ru: 'Иногда' },
      { id: 'never', zh: '没有接触过', ru: 'Нет' },
    ],
  },
  {
    id: 'C2',
    block: 'C',
    zh: '您希望看到来自俄罗斯远东地区的什么创意内容？（最多选3个）',
    ru: 'Какой креативный контент с Дальнего Востока России хотели бы видеть?',
    type: 'multiple',
    fieldName: 'desiredContent',
    maxChoices: 3,
    options: [
      { id: 'city_explore', zh: '城市探索视频', ru: 'Видео-прогулки по городу' },
      { id: 'ru_music', zh: '俄罗斯风格的音乐', ru: 'Русская музыка' },
      { id: 'street_photo', zh: '人文/街头摄影', ru: 'Стрит-фотография' },
      { id: 'ru_food', zh: '俄罗斯美食制作', ru: 'Готовка русской еды' },
      { id: 'nature', zh: '自然风景/极地风光', ru: 'Природа / пейзажи' },
      { id: 'ru_lang', zh: '俄语教学', ru: 'Уроки русского языка' },
      { id: 'shopping', zh: '购物攻略/好物推荐', ru: 'Шоппинг-гайды' },
      { id: 'student_life', zh: '留学生活日常', ru: 'Жизнь студентов' },
    ],
  },
  {
    id: 'C3',
    block: 'C',
    zh: '如果一位俄罗斯创作者专门为中国观众制作内容，您最可能在哪个平台关注？',
    ru: 'На какой платформе подписались бы на русского автора?',
    type: 'single',
    fieldName: 'preferredPlatform',
    options: [
      { id: 'douyin', zh: '抖音', ru: 'Douyin' },
      { id: 'red', zh: '小红书', ru: 'RED' },
      { id: 'bilibili', zh: '哔哩哔哩 (B站)', ru: 'Bilibili' },
      { id: 'wechat_ch', zh: '微信视频号', ru: 'WeChat Channels' },
      { id: 'kuaishou', zh: '快手', ru: 'Kuaishou' },
      { id: 'other', zh: '其他', ru: 'Другое' },
    ],
  },
  {
    id: 'C4',
    block: 'C',
    zh: '您是否愿意购买以俄罗斯远东为灵感的原创设计商品？（如T恤、明信片、海报、手机壳）',
    ru: 'Купили бы товар с дизайном Дальнего Востока России?',
    type: 'single',
    fieldName: 'buyVlkProduct',
    options: [
      { id: 'definitely', zh: '一定会买', ru: 'Точно куплю' },
      { id: 'probably', zh: '可能会买', ru: 'Скорее да' },
      { id: 'depends', zh: '要看具体商品', ru: 'Зависит от товара' },
      { id: 'unlikely', zh: '不太可能', ru: 'Скорее нет' },
      { id: 'no', zh: '不会买', ru: 'Нет' },
    ],
  },

  // ===== BLOCK D — Purchase Behavior =====
  {
    id: 'D1',
    block: 'D',
    zh: '您通常通过什么渠道购买海外商品？（可多选）',
    ru: 'Где покупаете зарубежные товары?',
    type: 'multiple',
    fieldName: 'purchaseChannels',
    skipIf: { field: 'buyVlkProduct', equals: 'no' },
    options: [
      { id: 'poizon', zh: '得物 (Poizon)', ru: 'Poizon / Dewu' },
      { id: 'taobao', zh: '淘宝/天猫', ru: 'Taobao / Tmall' },
      { id: '1688', zh: '1688', ru: '1688' },
      { id: 'pinduoduo', zh: '拼多多', ru: 'Pinduoduo' },
      { id: 'red_store', zh: '小红书商城', ru: 'RED Store' },
      { id: 'buyer', zh: '找代购', ru: 'Через байера' },
      { id: 'direct_ru', zh: '在俄罗斯当地直接购买', ru: 'Напрямую в России' },
      { id: 'other', zh: '其他', ru: 'Другое' },
    ],
  },
  {
    id: 'D2',
    block: 'D',
    zh: '您愿意为一件来自俄罗斯远东的原创设计商品（服饰/配饰/艺术品）花多少钱？',
    ru: 'Сколько готовы заплатить за дизайнерский товар с Дальнего Востока России?',
    type: 'single',
    fieldName: 'priceWillingness',
    skipIf: { field: 'buyVlkProduct', equals: 'no' },
    options: [
      { id: 'under50', zh: '50元以下', ru: 'Менее 50¥' },
      { id: '50-150', zh: '50–150元', ru: '50–150¥' },
      { id: '151-300', zh: '151–300元', ru: '151–300¥' },
      { id: '301-500', zh: '301–500元', ru: '301–500¥' },
      { id: '500plus', zh: '500元以上', ru: 'Более 500¥' },
    ],
  },
  {
    id: 'D3',
    block: 'D',
    zh: '购买独特商品时，以下因素对您的重要程度如何？（请排出前三名）',
    ru: 'Что важнее всего при покупке уникального товара? (ТОП-3)',
    type: 'ranking',
    fieldName: 'purchaseFactors',
    skipIf: { field: 'buyVlkProduct', equals: 'no' },
    rankTop: 3,
    options: [
      { id: 'price', zh: '价格合理', ru: 'Адекватная цена' },
      { id: 'quality', zh: '材料/做工质量', ru: 'Качество материалов' },
      { id: 'design', zh: '设计独特性', ru: 'Уникальность дизайна' },
      { id: 'brand_story', zh: '品牌故事/文化背景', ru: 'История бренда' },
      { id: 'friend_rec', zh: '朋友推荐', ru: 'Рекомендация друзей' },
      { id: 'kol_rec', zh: '博主/KOL推荐', ru: 'Рекомендация блогера' },
      { id: 'eco', zh: '环保/可持续理念', ru: 'Экологичность' },
    ],
  },

  // ===== BLOCK E — Open Questions =====
  {
    id: 'E1',
    block: 'E',
    zh: '您最希望在中国市场上看到来自俄罗斯远东地区的什么创意产品或内容？（请简短描述）',
    ru: 'Какой продукт или контент креативных индустрий Дальнего Востока России хотели бы видеть?',
    type: 'open',
    fieldName: 'openProduct',
    maxLength: 200,
  },
  {
    id: 'E2',
    block: 'E',
    zh: '您来自中国哪个城市（省份）？',
    ru: 'Из какого вы города (провинции)?',
    type: 'open',
    fieldName: 'openCity',
    maxLength: 50,
  },
]

export const blockNames: Record<string, { zh: string; ru: string }> = {
  A: { zh: '基本信息', ru: 'Демография' },
  B: { zh: '内容消费习惯', ru: 'Потребление контента' },
  C: { zh: '对俄罗斯远东创意内容的态度', ru: 'Отношение к креативным индустриям Дальнего Востока' },
  D: { zh: '购买行为', ru: 'Покупательское поведение' },
  E: { zh: '开放式问题', ru: 'Открытые вопросы' },
}

export const totalQuestions = questions.length
